name: Run Custom Shell Script

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./second-part/11/test.sh

      - name: Run the script
        run: ./second-part/11/test.sh
